from django.db import models
from django.utils.translation import gettext_lazy as _
from model_utils.models import TimeStampedModel

from apps.core.models import BaseUserTracked, IsActive
from apps.equipment import models as equipment_models
from apps.reports import choices
from apps.users import models as users_models


class Report(TimeStampedModel, BaseUserTracked, IsActive):
    """
    Report model.

    Represents inspection reports generated by external providers
    for equipment condition monitoring and predictive maintenance.
    """

    organization = models.ForeignKey(
        users_models.Organization,
        verbose_name=_("Organization"),
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="reports",
        help_text=_("Organization/Client associated with this report"),
    )
    machine = models.ForeignKey(
        equipment_models.Machine,
        verbose_name=_("Machine"),
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="reports",
        help_text=_("Machine/Equipment associated with this report"),
    )
    component = models.ForeignKey(
        equipment_models.Component,
        verbose_name=_("Component"),
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="reports",
        help_text=_("Component associated with this report"),
    )
    lab_number = models.CharField(
        _("Lab Number"),
        max_length=50,
        unique=True,
        help_text=_("Laboratory identification number (No. Lab)"),
    )
    lubricant = models.CharField(
        _("Lubricant"),
        max_length=200,
        blank=True,
        help_text=_("Lubricant type/brand used"),
    )
    lubricant_hours_kms = models.DecimalField(
        _("Lubricant Hours/Kms"),
        max_digits=12,
        decimal_places=2,
        null=True,
        blank=True,
        help_text=_("Hours or kilometers of lubricant usage"),
    )
    serial_number_code = models.CharField(
        _("Serial Number Code"),
        max_length=100,
        blank=True,
        help_text=_("Serial number code from the report (Cod./Num. De Serie)"),
    )
    sample_date = models.DateField(
        _("Sample Date"),
        null=True,
        blank=True,
        help_text=_("Date when the sample was taken (Fecha Muestra)"),
    )
    per_number = models.CharField(
        _("PER Number"),
        max_length=50,
        blank=True,
        help_text=_("PER identification number (No. PER)"),
    )
    reception_date = models.DateField(
        _("Reception Date"),
        null=True,
        blank=True,
        help_text=_("Date when the sample was received (Fecha de Recepción)"),
    )
    status = models.CharField(
        _("Status"),
        max_length=20,
        choices=choices.ReportStatus.choices,
        default=choices.ReportStatus.PENDING,
        help_text=_("Current status of the report"),
    )
    condition = models.CharField(
        _("Condition"),
        max_length=20,
        choices=choices.ReportCondition.choices,
        default=choices.ReportCondition.NORMAL,
        help_text=_("Equipment condition assessment"),
    )
    notes = models.TextField(
        _("Notes"),
        blank=True,
        help_text=_("Additional notes or observations"),
    )

    class Meta:
        verbose_name = _("Report")
        verbose_name_plural = _("Reports")
        ordering = ("-sample_date", "-created")
        indexes = [
            models.Index(fields=["lab_number"]),
            models.Index(fields=["per_number"]),
            models.Index(fields=["sample_date"]),
            models.Index(fields=["organization", "is_active"]),
            models.Index(fields=["machine", "is_active"]),
            models.Index(fields=["status"]),
            models.Index(fields=["condition"]),
        ]

    def __str__(self) -> str:
        """Return string representation of report."""
        return f"Report {self.lab_number} - {self.get_condition_display()}"
